git:
  depth: 5

stages:
  - "Build and Test"
  - "Package"

jobs:
  include:
    - stage: "Build and Test Java"
      language: java
      jdk: oraclejdk11
      before_script:
        - cd sample-application-backend
    - stage: "Build and Test Nodejs"
      language: node.js
      node_js: "12.20"
      before_script:
        - cd sample-application-frontend
    - stage: "Package"
      before_script:
        - cd sample-application-backend
      script:
        - docker build -t ${DOCKERUSR}/sample-application-backend .
        - docker login -u $DOCKERUSR -p $DOCKERPWD
        - docker push ${DOCKERUSR}/sample-application-backend
    - stage: "Package"
      before_script:
        - cd sample-application-frontend
      script:
        - docker build -t ${DOCKERUSR}/sample-application-frontend .
        - docker login -u $DOCKERUSR -p $DOCKERPWD
        - docker push ${DOCKERUSR}/sample-application-frontend

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.npm"