git:
  depth: 5

stages:
  - "Build and Test"
  - "Package"

jobs:
  include:
    - stage: "Build and Test Java"
      language: java
      jdk: oraclejdk11
      before_script:
        - cd sample-application-backend
    - stage: "Build and Test Nodejs"
      language: node.js
      node_js: "12.20"
      before_script:
        - cd sample-application-frontend
    - stage: "Package"
      before_script:
        - cd sample-application-backend
      script:
        - docker-compose build
        - docker login -up $DOCKERUSR $DOCKERPWD
        - docker-compose push 
    - stage: "Package"
      before_script:
        - cd sample-application-frontend
      script:
        - docker-compose build
        - docker login -up $DOCKERUSR $DOCKERPWD
        - docker-compose push 

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.npm"